### ISSUE TITLE
Ontology Development

### ISSUE THREAD

**Issue by Gautamshahi** [TIBHannover/diaspora#14]
Update the existing ontology 

- [x] Prepare a list of all properties in an excel file
- [ ] Reuse the existing ontology (List is shared below)
- [ ] Get the feedback from Javad
- [ ] Get feedback from Lorenz
- [ ] Present it in the status meeting
- [ ] Make a documentation
- [ ] Finalise the ontology
- [ ] Publish the ontology(already finalised, listed below)

**Comment by InquisitiveVi** [comment]
Hi Javad, 
Just commenting here for the development of BacDive upper ontology.

**Comment by javadch** [comment]
dev will continue on #22
