### ISSUE TITLE
Implementation for bacdive version - 1.1 

### ISSUE THREAD

**Issue by rohit252** [TIBHannover/diaspora#17]
- [ ] Making separate classes for the column names which are common in multiple tables. 
- [ ] Empty columns to be presented/ cleared ( Ask Lorenz).
- [ ] Applying restrictions on columns.

**Comment by javadch** [comment]
- [ ] Integrate the new tables (Verions1.1) into the pipeline
- [ ] Refactor the mappings to have the relationships started from the strain class
