### ISSUE TITLE
Generate BacDive upper ontology (BDO) v0.00 - concepts & properties, controlled vocabularies

### ISSUE THREAD

**Issue by javadch** [TIBHannover/diaspora#19]

**Comment by javadch** [comment]
[List of tables and their inter relationships](https://github.com/TIBHannover/diaspora/blob/main/wp2/t2.1/BD_table_v2.csv)

**Comment by javadch** [comment]
List of potentially useful ontologies:
- [ ] BioPortal (https://bioportal.bioontology.org/)
- [ ] Obo foundry (http://www.obofoundry.org/)
- [ ] OLS at EBI (https://www.ebi.ac.uk/ols/)
- [ ] TIB (http://ontology.tib.eu/)

**Comment by javadch** [comment]
Use this as a template:
https://github.com/stream-project/ontology/blob/master/MatVoc-Core.ttl

Define the main concepts and link them to known concepts via owl:equivalentClass or other OWL terms like subclass, ...

**Comment by InquisitiveVi** [comment]
[List of new tables and their inter relationships](https://github.com/TIBHannover/diaspora/blob/main/wp2/t2.1/BD_table_v2_0.csv)
