### ISSUE TITLE
Make the pipeline multi DB version compatible

### ISSUE THREAD

**Issue by javadch** [TIBHannover/diaspora#25]
- [x] Separate the data from the container images
- [x] Make sure one GraphDb container instance can host multiple versions of the database at the same time
- [x] Make sure running the pipeline for version `n+1` does not break because version `n` already exists.

**Comment by javadch** [comment]
- [ ] A demo on the 3rd of Feb.

**Comment by rohit252** [comment]
pipeline is working now.
